[2016-01-05 20:46:59,116] {/Users/roporter/Desktop/Development/Python/myAPI/app/classes/requests.py->after_request:35} INFO - [97mINFO: [39mInside Main->returnResponse | app.after_request
[2016-01-05 20:47:19,954] {/Users/roporter/Desktop/Development/Python/myAPI/app/classes/requests.py->after_request:35} INFO - [97mINFO: [39mInside Main->returnResponse | app.after_request
[2016-01-05 20:47:20,390] {/Users/roporter/Desktop/Development/Python/myAPI/app/classes/requests.py->after_request:35} INFO - [97mINFO: [39mInside Main->returnResponse | app.after_request
[2016-01-05 20:47:20,481] {main.py->handle_error:54} INFO - [97mINFO: [39mInside Main->handle_error | app.errorhandler( Exception )
[2016-01-05 20:47:20,482] {/Users/roporter/Desktop/Development/Python/myAPI/app/classes/requests.py->after_request:35} INFO - [97mINFO: [39mInside Main->returnResponse | app.after_request
[2016-01-05 20:47:20,546] {main.py->handle_error:54} INFO - [97mINFO: [39mInside Main->handle_error | app.errorhandler( Exception )
[2016-01-05 20:47:20,546] {/Users/roporter/Desktop/Development/Python/myAPI/app/classes/requests.py->after_request:35} INFO - [97mINFO: [39mInside Main->returnResponse | app.after_request
[2016-01-05 20:47:20,678] {main.py->handle_error:54} INFO - [97mINFO: [39mInside Main->handle_error | app.errorhandler( Exception )
[2016-01-05 20:47:20,679] {/Users/roporter/Desktop/Development/Python/myAPI/app/classes/requests.py->after_request:35} INFO - [97mINFO: [39mInside Main->returnResponse | app.after_request
[2016-01-05 20:48:16,872] {/Users/roporter/Desktop/Development/Python/myAPI/app/classes/requests.py->after_request:35} INFO - [97mINFO: [39mInside Main->returnResponse | app.after_request
[2016-01-05 20:48:17,209] {/Users/roporter/Desktop/Development/Python/myAPI/app/classes/requests.py->after_request:35} INFO - [97mINFO: [39mInside Main->returnResponse | app.after_request
[2016-01-05 20:48:17,260] {main.py->handle_error:54} INFO - [97mINFO: [39mInside Main->handle_error | app.errorhandler( Exception )
[2016-01-05 20:48:17,261] {/Users/roporter/Desktop/Development/Python/myAPI/app/classes/requests.py->after_request:35} INFO - [97mINFO: [39mInside Main->returnResponse | app.after_request
[2016-01-05 20:48:17,339] {main.py->handle_error:54} INFO - [97mINFO: [39mInside Main->handle_error | app.errorhandler( Exception )
[2016-01-05 20:48:17,340] {/Users/roporter/Desktop/Development/Python/myAPI/app/classes/requests.py->after_request:35} INFO - [97mINFO: [39mInside Main->returnResponse | app.after_request
[2016-01-05 20:48:17,430] {main.py->handle_error:54} INFO - [97mINFO: [39mInside Main->handle_error | app.errorhandler( Exception )
[2016-01-05 20:48:17,431] {/Users/roporter/Desktop/Development/Python/myAPI/app/classes/requests.py->after_request:35} INFO - [97mINFO: [39mInside Main->returnResponse | app.after_request
[2016-01-05 20:48:51,735] {/Users/roporter/Desktop/Development/Python/myAPI/app/classes/requests.py->after_request:35} INFO - [97mINFO: [39mInside Main->returnResponse | app.after_request
[2016-01-05 20:48:52,173] {/Users/roporter/Desktop/Development/Python/myAPI/app/classes/requests.py->after_request:35} INFO - [97mINFO: [39mInside Main->returnResponse | app.after_request
[2016-01-05 20:48:52,255] {main.py->handle_error:54} INFO - [97mINFO: [39mInside Main->handle_error | app.errorhandler( Exception )
[2016-01-05 20:48:52,256] {/Users/roporter/Desktop/Development/Python/myAPI/app/classes/requests.py->after_request:35} INFO - [97mINFO: [39mInside Main->returnResponse | app.after_request
[2016-01-05 20:48:52,351] {main.py->handle_error:54} INFO - [97mINFO: [39mInside Main->handle_error | app.errorhandler( Exception )
[2016-01-05 20:48:52,353] {/Users/roporter/Desktop/Development/Python/myAPI/app/classes/requests.py->after_request:35} INFO - [97mINFO: [39mInside Main->returnResponse | app.after_request
[2016-01-05 20:48:52,500] {main.py->handle_error:54} INFO - [97mINFO: [39mInside Main->handle_error | app.errorhandler( Exception )
[2016-01-05 20:48:52,501] {/Users/roporter/Desktop/Development/Python/myAPI/app/classes/requests.py->after_request:35} INFO - [97mINFO: [39mInside Main->returnResponse | app.after_request
[2016-01-05 20:49:08,272] {/Users/roporter/Desktop/Development/Python/myAPI/app/classes/requests.py->after_request:35} INFO - [97mINFO: [39mInside Main->returnResponse | app.after_request
[2016-01-05 20:49:08,726] {/Users/roporter/Desktop/Development/Python/myAPI/app/classes/requests.py->after_request:35} INFO - [97mINFO: [39mInside Main->returnResponse | app.after_request
[2016-01-05 20:49:09,018] {main.py->handle_error:54} INFO - [97mINFO: [39mInside Main->handle_error | app.errorhandler( Exception )
[2016-01-05 20:49:09,019] {/Users/roporter/Desktop/Development/Python/myAPI/app/classes/requests.py->after_request:35} INFO - [97mINFO: [39mInside Main->returnResponse | app.after_request
[2016-01-05 20:49:09,146] {main.py->handle_error:54} INFO - [97mINFO: [39mInside Main->handle_error | app.errorhandler( Exception )
[2016-01-05 20:49:09,147] {/Users/roporter/Desktop/Development/Python/myAPI/app/classes/requests.py->after_request:35} INFO - [97mINFO: [39mInside Main->returnResponse | app.after_request
[2016-01-05 20:49:09,254] {main.py->handle_error:54} INFO - [97mINFO: [39mInside Main->handle_error | app.errorhandler( Exception )
[2016-01-05 20:49:09,255] {/Users/roporter/Desktop/Development/Python/myAPI/app/classes/requests.py->after_request:35} INFO - [97mINFO: [39mInside Main->returnResponse | app.after_request
[2016-01-05 20:49:17,348] {/Users/roporter/Desktop/Development/Python/myAPI/app/classes/requests.py->after_request:35} INFO - [97mINFO: [39mInside Main->returnResponse | app.after_request
[2016-01-05 20:49:17,727] {/Users/roporter/Desktop/Development/Python/myAPI/app/classes/requests.py->after_request:35} INFO - [97mINFO: [39mInside Main->returnResponse | app.after_request
[2016-01-05 20:49:17,778] {main.py->handle_error:54} INFO - [97mINFO: [39mInside Main->handle_error | app.errorhandler( Exception )
[2016-01-05 20:49:17,779] {/Users/roporter/Desktop/Development/Python/myAPI/app/classes/requests.py->after_request:35} INFO - [97mINFO: [39mInside Main->returnResponse | app.after_request
[2016-01-05 20:49:17,833] {main.py->handle_error:54} INFO - [97mINFO: [39mInside Main->handle_error | app.errorhandler( Exception )
[2016-01-05 20:49:17,834] {/Users/roporter/Desktop/Development/Python/myAPI/app/classes/requests.py->after_request:35} INFO - [97mINFO: [39mInside Main->returnResponse | app.after_request
[2016-01-05 20:49:17,976] {main.py->handle_error:54} INFO - [97mINFO: [39mInside Main->handle_error | app.errorhandler( Exception )
[2016-01-05 20:49:17,978] {/Users/roporter/Desktop/Development/Python/myAPI/app/classes/requests.py->after_request:35} INFO - [97mINFO: [39mInside Main->returnResponse | app.after_request
[2016-01-05 20:49:59,052] {/Users/roporter/Desktop/Development/Python/myAPI/app/classes/requests.py->after_request:35} INFO - [97mINFO: [39mInside Main->returnResponse | app.after_request
[2016-01-05 20:49:59,454] {/Users/roporter/Desktop/Development/Python/myAPI/app/classes/requests.py->after_request:35} INFO - [97mINFO: [39mInside Main->returnResponse | app.after_request
[2016-01-05 20:49:59,563] {main.py->handle_error:54} INFO - [97mINFO: [39mInside Main->handle_error | app.errorhandler( Exception )
[2016-01-05 20:49:59,564] {/Users/roporter/Desktop/Development/Python/myAPI/app/classes/requests.py->after_request:35} INFO - [97mINFO: [39mInside Main->returnResponse | app.after_request
[2016-01-05 20:49:59,658] {main.py->handle_error:54} INFO - [97mINFO: [39mInside Main->handle_error | app.errorhandler( Exception )
[2016-01-05 20:49:59,659] {/Users/roporter/Desktop/Development/Python/myAPI/app/classes/requests.py->after_request:35} INFO - [97mINFO: [39mInside Main->returnResponse | app.after_request
[2016-01-05 20:49:59,769] {main.py->handle_error:54} INFO - [97mINFO: [39mInside Main->handle_error | app.errorhandler( Exception )
[2016-01-05 20:49:59,770] {/Users/roporter/Desktop/Development/Python/myAPI/app/classes/requests.py->after_request:35} INFO - [97mINFO: [39mInside Main->returnResponse | app.after_request
[2016-01-05 20:50:48,323] {/Users/roporter/Desktop/Development/Python/myAPI/app/classes/requests.py->after_request:35} INFO - [97mINFO: [39mInside Main->returnResponse | app.after_request
[2016-01-05 20:50:48,710] {/Users/roporter/Desktop/Development/Python/myAPI/app/classes/requests.py->after_request:35} INFO - [97mINFO: [39mInside Main->returnResponse | app.after_request
[2016-01-05 20:50:48,758] {main.py->handle_error:54} INFO - [97mINFO: [39mInside Main->handle_error | app.errorhandler( Exception )
[2016-01-05 20:50:48,759] {/Users/roporter/Desktop/Development/Python/myAPI/app/classes/requests.py->after_request:35} INFO - [97mINFO: [39mInside Main->returnResponse | app.after_request
[2016-01-05 20:50:48,813] {main.py->handle_error:54} INFO - [97mINFO: [39mInside Main->handle_error | app.errorhandler( Exception )
[2016-01-05 20:50:48,814] {/Users/roporter/Desktop/Development/Python/myAPI/app/classes/requests.py->after_request:35} INFO - [97mINFO: [39mInside Main->returnResponse | app.after_request
[2016-01-05 20:50:48,932] {main.py->handle_error:54} INFO - [97mINFO: [39mInside Main->handle_error | app.errorhandler( Exception )
[2016-01-05 20:50:48,933] {/Users/roporter/Desktop/Development/Python/myAPI/app/classes/requests.py->after_request:35} INFO - [97mINFO: [39mInside Main->returnResponse | app.after_request
[2016-01-05 20:51:26,437] {/Users/roporter/Desktop/Development/Python/myAPI/app/classes/requests.py->after_request:35} INFO - [97mINFO: [39mInside Main->returnResponse | app.after_request
[2016-01-05 20:51:26,695] {main.py->handle_error:54} INFO - [97mINFO: [39mInside Main->handle_error | app.errorhandler( Exception )
